site_name: Data Catalogue Guide
site_author: Archaeology Data Service
repo_name: ads-data-catalogue-docs
repo_url: https://github.com/uoy-ads/ads-data-catalogue-docs/
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/ads_logo_white.png
  favicon: assets/ads_logo.png
  features:
    - navigation.sections    # Groups top-level sections in sidebar
    - navigation.instant     # Faster page transitions
    - navigation.top         # Back-to-top button
    - navigation.footer      # Links to previous and next page
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: white

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: green

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption

extra:
  social:
    - icon: simple/bluesky
      link: https://bsky.app/profile/ads-update.bsky.social
      name: ADS Bluesky
    - icon: simple/facebook
      link: https://www.facebook.com/archaeology.data.service/
      name: ADS Facebook
    - icon: simple/instagram
      link: https://www.instagram.com/archaeologydataservice/
      name: ADS Instagram
copyright: Copyright &copy; 2025 - Archaeology Data Service

nav:
  - Home: index.md
  - Searching the Catalogue: Section-0_Searching_Catalogue.md
  - Search parameters:
    - What - The Text tool: Section-1_What.md
    - Where - The Map tool: Section-2_Map_Where.md
    - When - The Time period tool: Section-3_Time_period_When.md
  - Search Filters: Section-4_Search_Filters.md
  - The Resource Page: Section-5_Resources.md
  - Tips and Guidance: Section-6_Tips_and_guidance.md
  - Tips and Guidance 2: Section-6_edit.md
  - RDA metadata: RDA_metadata.md